"""Orquesta los runners EN PARALELO y normaliza el resultado."""
import asyncio, time, json, uuid
from datetime import datetime, timezone
import httpx
from .runners import ALL_RUNNERS
from .netguard import ClienteSeguro
from .runners.nuclei import run as nuclei_run
from . import brand
from .schema import Finding, score, grade

ENGINE_VERSION = "0.13.2"

HEADERS = {"User-Agent": brand.USER_AGENT}
ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
EFFORT_ORDER = {"low": 0, "medium": 1, "high": 2}


# CDN que ocultan el origen: si hay uno delante, las cabeceras del
# servidor real no llegan y hay capas que NO se pueden determinar.
CDN_SERVERS = ("cloudflare", "sucuri", "akamai", "fastly", "cloudfront",
               "incapsula", "vercel", "netlify", "openresty")

# Que runner alimenta cada capa del informe, y si depende de HTTP.
# (capa, runner, necesita_http, que cuenta como "determinado")
#
# La ultima columna importa: que un runner devuelva ALGO no significa
# que determinara lo que la capa promete. El runner de stack emite
# meta.server siempre, pero la capa solo esta cubierta si vio el PHP.
AREAS = (
    ("tls",      "tls",       False, None),
    ("dns",      "dns_mail",  False, None),
    ("headers",  "headers",   True,  None),
    ("exposure", "exposure",  True,  None),
    ("cms",      "wordpress", True,  None),
    ("stack",    "stack",     True,  "php"),
)


APP_STATES = {
    "not_requested": ("undetermined", "deep_scan_not_requested"),
    "throttled":     ("undetermined", "throttled_during_scan"),
    "incomplete":    ("partial",      "budget_exhausted"),
    "generic_only":  ("partial",      "cms_unknown_no_cve_pass"),
    "error":         ("error",        None),
    "ok":            ("ok",           None),
}


def _coverage(findings, errors, site, http_blocked: str | None,
              app_state: str = "not_requested") -> dict:
    """Declara que se reviso, que se pudo determinar y que no, y por que.

    Sin esto, el informe no distingue "no lo encontre" de "no existe",
    y el cliente asume que la capa no se reviso.
    """
    server = str((site.get("server") or {}).get("server", "")).lower()
    cdn_reason = ("origin_behind_cdn"
                  if any(c in server for c in CDN_SERVERS) else None)

    by_source: dict[str, list] = {}
    for f in findings:
        by_source.setdefault(f.source, []).append(f)

    fallback = {
        "cms": cdn_reason or "cms_not_recognised",
        "stack": cdn_reason or "version_not_disclosed",
    }

    cov: dict[str, dict] = {}
    for area, source, needs_http, key_marker in AREAS:
        produced = by_source.get(source, [])
        if key_marker:
            produced = [f for f in produced if key_marker in f.finding_key]

        if needs_http and http_blocked:
            cov[area] = {"checked": False, "result": "undetermined",
                         "reason": http_blocked}
        elif source in errors:
            cov[area] = {"checked": True, "result": "error",
                         "reason": errors[source]}
        elif produced:
            cov[area] = {"checked": True, "result": "ok"}
        else:
            cov[area] = {"checked": True, "result": "undetermined",
                         "reason": fallback.get(area, "no_data")}

    result, reason = APP_STATES[app_state]
    cov["app"] = {"checked": app_state not in ("not_requested",),
                  "result": result}
    if reason:
        cov["app"]["reason"] = reason
    elif app_state == "error":
        cov["app"]["reason"] = errors.get("nuclei", "error")
    return cov


# Solo cuentan las cabeceras que indican MITIGACION. cf-ray o
# cf-edge-cache aparecen en CUALQUIER sitio detras de Cloudflare, tambien
# cuando responde con normalidad, asi que no sirven como senal de bloqueo.
WAF_HEADERS = ("cf-mitigated", "x-sucuri-block", "x-iinfo")

# Firmas de paginas de desafio por producto. Imunify360 WebShield es el
# mas comun en hosting compartido con cPanel, muy extendido en
# Latinoamerica, asi que va a aparecer a menudo.
WAF_PRODUCTS = {
    "imunify360": ("wsidchk", "your request is being verified",
                   "z0f76a1d14fd21a8fb5fd0d03e0fdc3d3cedae52f"),
    "cloudflare": ("checking your browser", "just a moment",
                   "cf-challenge", "attention required"),
    "sucuri": ("sucuri website firewall", "access denied - sucuri"),
    "wordfence": ("generated by wordfence", "wordfence-blocked"),
    "modsecurity": ("mod_security", "modsecurity", "not acceptable!"),
    "generic": ("enable javascript", "verifying you are human",
                "ddos protection"),
}

DENIED = (403, 406, 429, 503)
THROTTLED = (429, 503)
RETRY_WAIT_S = 4


def _waf_signature(r) -> tuple[list[str], str | None]:
    """Devuelve (cabeceras de mitigacion, producto) si la respuesta es de
    un WAF. Sin firma no se puede afirmar que haya un firewall."""
    hits = [h for h in WAF_HEADERS if h in r.headers]
    body_lc = r.text[:8000].lower()
    product = next((name for name, sigs in WAF_PRODUCTS.items()
                    if any(sig in body_lc for sig in sigs)), None)
    if hits and not product:
        product = {"cf-mitigated": "cloudflare", "x-sucuri-block": "sucuri",
                   "x-iinfo": "incapsula"}[hits[0]]
    return hits, product


def _log(target: str, msg: str) -> None:
    # Sin esto, un "bloqueado" en el informe no se puede auditar: el log
    # solo decia "escaneando" y "listo".
    print(f"[integrity] {target} {msg}", flush=True)


async def _integrity_check(target: str, client) -> dict:
    """Comprueba que el servidor responde de forma honesta.

    Pide una ruta aleatoria que no puede existir. Si devuelve 200, o bien
    el sitio responde 200 a todo (soft 404), o alguien esta interceptando
    el trafico. En ambos casos NADA de lo que llegue por HTTP es fiable:
    un 200 en /.env no significaria que el archivo existe.

    Un 403 en esa ruta NO basta para decir "firewall": muchos hostings
    (LiteSpeed, ModSecurity) prohiben rutas concretas y sirven la portada
    con normalidad. Solo se declara WAF con una firma reconocible, y solo
    se declara bloqueo si la PORTADA tambien se rechaza.
    """
    base = target.rstrip("/")
    nonce = uuid.uuid4().hex[:16]
    probe = f"{base}/{brand.PROBE_PREFIX}-{nonce}"
    try:
        r = await client.get(probe)
    except Exception as e:
        _log(target, f"probe_failed {type(e).__name__}: {e}")
        return {"ok": False, "reason": "probe_failed", "detail": str(e)}

    hits, product = _waf_signature(r)
    challenge = product is not None
    _log(target, f"probe status={r.status_code} server={r.headers.get('server')} "
                 f"waf={product} signals={hits}")

    # 1) Firma de WAF reconocible: bloqueo confirmado, sea cual sea el
    #    codigo (los desafios de Cloudflare/Imunify suelen llegar con 200).
    if challenge and (r.status_code in DENIED or r.status_code == 200):
        return {
            "ok": False,
            "reason": "waf_blocked",
            "detail": ("El sitio esta protegido por un firewall de aplicacion "
                       "que bloqueo el escaneo automatizado."),
            "signals": hits,
            "product": product,
            "challenge_page": True,
            "status": r.status_code,
            "server": r.headers.get("server"),
        }

    # 2) Rechazo SIN firma: miramos la portada antes de concluir nada.
    if r.status_code in DENIED:
        if r.status_code in THROTTLED:
            # Un 429/503 puede ser un limite pasajero: esperamos y
            # repetimos la prueba una vez antes de juzgar.
            await asyncio.sleep(RETRY_WAIT_S)
            try:
                r2 = await client.get(probe)
                _log(target, f"probe retry status={r2.status_code}")
                if r2.status_code not in DENIED:
                    r = r2
            except Exception as e:
                _log(target, f"probe retry failed {type(e).__name__}: {e}")

    if r.status_code in DENIED:
        try:
            home = await client.get(base + "/")
        except Exception as e:
            _log(target, f"home failed {type(e).__name__}: {e}")
            home = None

        if home is not None:
            h_hits, h_product = _waf_signature(home)
            # Una portada NORMAL puede contener "enable javascript" en un
            # <noscript>. Con 200, solo cuentan firmas inequivocas.
            if (h_product and home.status_code not in DENIED and not h_hits
                    and h_product not in ("imunify360", "sucuri")):
                h_product = None
            _log(target, f"home status={home.status_code} waf={h_product}")

            if h_product:
                return {
                    "ok": False,
                    "reason": "waf_blocked",
                    "detail": ("El sitio esta protegido por un firewall de "
                               "aplicacion que bloqueo el escaneo automatizado."),
                    "signals": h_hits,
                    "product": h_product,
                    "challenge_page": True,
                    "status": home.status_code,
                    "server": home.headers.get("server"),
                }

            if home.status_code < 400:
                # La portada responde bien: el rechazo era solo de esa
                # ruta. HTTP es fiable (no es un soft 404) y seguimos.
                _log(target, f"ok: probe {r.status_code} solo en la ruta, "
                             "portada normal")
                return {"ok": True, "probe_status": r.status_code,
                        "note": "probe_path_denied"}

            if home.status_code in THROTTLED:
                return {
                    "ok": False,
                    "reason": "rate_limited",
                    "detail": ("El sitio limito nuestras peticiones y no "
                               "pudimos completar el analisis."),
                    "status": home.status_code,
                    "server": home.headers.get("server"),
                }

        # Portada rechazada (o inalcanzable) sin firma de WAF: hay un
        # bloqueo, pero no sabemos de que. No afirmamos "firewall".
        return {
            "ok": False,
            "reason": "access_denied",
            "detail": ("El sitio rechazo las peticiones de nuestro escaner, "
                       "por lo que no pudimos completar el analisis."),
            "status": home.status_code if home is not None else r.status_code,
            "server": (home or r).headers.get("server"),
        }

    if r.status_code == 200:
        return {
            "ok": False,
            "reason": "responds_200_to_everything",
            "detail": ("El servidor devuelve 200 a rutas inexistentes. "
                       "Puede ser un soft 404 o interceptacion de red."),
            "probe_url": probe,
            "server": r.headers.get("server"),
            "body_preview": r.text[:160],
        }
    return {"ok": True, "probe_status": r.status_code}


async def scan(target: str, deep: bool = False) -> dict:
    started = time.time()
    errors: dict[str, str] = {}

    limits = httpx.Limits(max_connections=10)
    async with ClienteSeguro(
        timeout=15, headers=HEADERS,
        limits=limits, verify=True,
    ) as client:
        async def guarded(name, fn):
            try:
                return await fn(target, client)
            except Exception as e:
                errors[name] = f"{type(e).__name__}: {e}"
                return []

        integrity = await _integrity_check(target, client)
        http_ok = integrity["ok"]
        http_blocked = None if http_ok else integrity["reason"]

        # Si no podemos confiar en HTTP, corremos SOLO los runners que no
        # dependen de el. Mejor un informe parcial y honesto que ninguno.
        # Fase 1: todos los runners pasivos, en paralelo.
        selected = [(n, fn) for n, fn, needs_http in ALL_RUNNERS
                    if n != "nuclei" and (http_ok or not needs_http)]
        results = await asyncio.gather(*[guarded(n, fn) for n, fn in selected])
        findings: list[Finding] = [f for group in results for f in group]

        # Fase 2: nuclei, alimentado con el CMS que acabamos de detectar.
        # Sin esa pista lanzaria miles de CVEs de productos irrelevantes.
        app_state = "not_requested"
        if deep and http_ok:
            cms = next((f.evidence.get("cms") for f in findings
                        if f.finding_key == "meta.cms"), None)
            try:
                found = await nuclei_run(target, client, deep=True, cms=cms)
                findings += found

                # Cero hallazgos puede significar "limpio" o "nos
                # bloquearon a mitad". Reintentamos la prueba de
                # integridad: si ahora nos rechazan, fue lo segundo.
                after = await _integrity_check(target, client)
                if not after["ok"]:
                    app_state = "throttled"
                elif any(f.finding_key == "nuclei.timed_out" for f in found):
                    app_state = "incomplete"
                elif not cms:
                    # Sin CMS conocido no corrimos la pasada de CVEs. Decir
                    # "sin vulnerabilidades" aqui seria una tranquilidad
                    # falsa: lo unico que sabemos es que la pasada generica
                    # no encontro nada.
                    app_state = "generic_only"
                else:
                    app_state = "ok"
            except Exception as e:
                errors["nuclei"] = f"{type(e).__name__}: {e}"
                app_state = "error"

        # Sin vulnerabilidades es una fortaleza, pero solo puede afirmarse
        # con el alcance que realmente se cubrio.
        clean = not any(f.source == "nuclei" and f.severity != "info"
                        for f in findings)
        if clean and app_state in ("ok", "generic_only"):
            key = ("ok.app.no_known_vulns" if app_state == "ok"
                   else "ok.app.no_generic_vulns")
            findings.append(Finding(
                key, "app", "nuclei", "info", "firm", "low",
                evidence={"cms": cms, "scope": app_state}))

    if http_blocked == "waf_blocked":
        findings.append(Finding(
            "ok.waf.protected", "surface", "integrity",
            "info", "firm", "low",
            evidence={"product": integrity.get("product"),
                      "status": integrity.get("status")},
        ))

    # Prioriza por riesgo alto + esfuerzo bajo. Eso es lo que hace
    # que un informe se sienta util en vez de aterrador.
    findings.sort(key=lambda f: (ORDER[f.severity], EFFORT_ORDER[f.effort]))

    # Un informe que solo enumera problemas se lee como venta por miedo.
    # Separamos lo que el sitio hace BIEN para que el PDF abra con eso.
    site = {f.finding_key[5:]: f.evidence
            for f in findings if f.finding_key.startswith("meta.")}
    strengths = [f for f in findings if f.finding_key.startswith("ok.")]
    issues = [f for f in findings
              if not f.finding_key.startswith(("ok.", "meta."))]

    # Solo puntuamos un analisis completo. Una nota calculada sobre dos
    # capas de seis seria enganosa: parece buena por lo que no se vio.
    value = score([f for f in issues if f.severity != "info"]) if http_ok else None

    out = {
        "engine_version": ENGINE_VERSION,
        "scanned_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "target": target,
        "scan_mode": ("deep" if deep else "full") if http_ok else "partial",
        "reliable": http_ok,
        "score": value,
        "grade": grade(value) if value is not None else None,
        "duration_s": round(time.time() - started, 2),
        "counts": {s: sum(1 for f in issues if f.severity == s) for s in ORDER},
        "site": site,
        "coverage": _coverage(findings, errors, site, http_blocked, app_state),
        "strengths": [f.to_dict() for f in strengths],
        "findings": [f.to_dict() for f in issues],
        "errors": errors,
    }
    if not http_ok:
        out["integrity"] = integrity
    return out


if __name__ == "__main__":
    import sys
    url = sys.argv[1] if len(sys.argv) > 1 else "https://example.com"
    deep = "--deep" in sys.argv
    print(json.dumps(asyncio.run(scan(url, deep=deep)), indent=2, ensure_ascii=False))
